config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "application#index"

  
    resources :projects, except: [:index, :show]
    resources :users do
      member do
        patch :archive 
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      member do
        patch :watch
      end
    end
  end

  scope path: "tickets/:ticket_id", as: :ticket do
    resources :comments, only: [:create]
    delete "tags/remove/:id", to: "tags#remove", as: :remove_tag
  end
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    has_many :tickets, dependent: :delete_all
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
    before_action :set_project, only: %i(show edit update destroy)


    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)

        if @project.save
            flash[:notice] = "Project has been created."
            redirect_to @project
        else
            flash.now[:alert] = "Project has not been created."
            render "new"
        end
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        if @project.update(project_params)
            flash[:notice] = "Project has been updated."
            redirect_to @project
        else
            flash.now[:alert] = "Project has not been updated."
            render "edit"
        end
    end

    def destroy
        @project.destroy

        flash[:notice] = "Project has been deleted."
        redirect_to projects_path
    end

    private

    def project_params
        params.require(:project).permit(:name, :description)
    end

    def set_project
        @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking for could not be found."
        redirect_to projects_path
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: %i(show edit update destroy)

    def index
        @projects = Project.all
    end

    def show
    end
    
    private

    def project_params
        params.require(:project).permit(:name, :description)
    end

    def set_project
        @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking for could not be found."
        redirect_to projects_path
    end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= bootstrap_form_with(model: project, local: true, label_errors: true) do |form| %>
    <%= form.text_field :name %>
    <%= form.text_field :description %>

    <%= form.primary %>
<% end %>

app/views/projects/index.html.erb
<header>

<h1> Projects </h1>

<div class="projects">
    <% @projects.each do |project| %>
        <h2><%= link_to project.name, project %></h2>
        <p><%= project.description %></p>
    <% end %>
</div>

<% admins_only do %>
    <ul class="actions">
        <li><%= link_to "New Project", new_admin_project_path,
            class: "new" %>
        </li>
    </ul>
<% end %>

</header>

app/views/projects/show.html.erb
<header>

<% title @project.name, "Projects" %>

<h1><%= @project.name %></h1>

<p><%= @project.description %></p>

<% admins_only do %>
    <ul class="actions">
        <li><%= link_to "Edit Project", edit_admin_project_path(@project), class: "edit" %>
        </li>

        <li><%= button_to "Delete Project",
            admin_project_path(@project),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this project?" },
            class: "delete"
            %>
        </li>
    </ul>
<% end %>


</header>

<header>
    <h2>Tickets</h2>

    <ul class="tickets">
        <% @project.tickets.each do |ticket| %>
            <li>
                #<%= ticket.id %> -
                <%= link_to ticket.name, [@project, ticket] %>
            </li>
        <% end %>
    </ul>

    <ul class="actions">
        <li><%= link_to "New Ticket", new_project_ticket_path(@project) %></li>
    </ul>
    
</header>