config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "application#index"

  
    resources :projects, except: [:index, :show]
    resources :users do
      member do
        patch :archive 
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      member do
        patch :watch
      end
    end
  end

  scope path: "tickets/:ticket_id", as: :ticket do
    resources :comments, only: [:create]
    delete "tags/remove/:id", to: "tags#remove", as: :remove_tag
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :active, lambda { where(archived_at: nil) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User" })"
  end

  def archive!
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: %i(show edit update destroy archive)

  def index
    @users = User.active.order(:email)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!"
    else
      @user.archive!
      flash[:notice] = "User has been archived."
    end
    
    redirect_to admin_users_path
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= bootstrap_form_with(model: [:admin, user], local: true, label_errors: true) do |form| %>
    <%= form.text_field :email %>
    <%= form.password_field :password %>
    <%= form.check_box :admin, label: "Is an admin?" %>

    <%= form.primary %>
<% end %>

app/views/admin/users/edit.html.erb
<header>
    <h1> Edit User </h1>
</header>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<header>
    <h1> Users </h1>

    <ul class="actions">
        <li>
            <%= link_to "New User", new_admin_user_path, class: "new" %>
        </li>
    </ul>
</header>

<ul>
    <% @users.each do |user| %>
        <li> <%= link_to user, [:admin, user] %></li>
    <% end %>
</ul>

app/views/admin/users/new.html.erb
<header>
    <h1> New User </h1>
</header>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<header>
    <h1><%= @user %></h1>

    <ul class="actions">
        <li>
            <%= link_to "Edit User", [:edit, :admin, @user], class: "edit" %>
        </li>
        <li>
            <%= link_to "Archive User", [:archive, :admin, @user], method: :patch, data: { confirm: "Are you sure you want to archive this user?" }, class: "delete" %>
        </li>
    </ul>
</header>